CLIP_FPS_FOR_RTC    = 14.635

ONE_SECOND_FRAMES   = int(CLIP_FPS_FOR_RTC*1+1)
ONE_MINUTE_FRAMES   = int(CLIP_FPS_FOR_RTC*60+1)

NOISE_WINDOW_SEC  = 10
NOISE_WINDOW_FRAME  = int(CLIP_FPS_FOR_RTC*NOISE_WINDOW_SEC)

MIN_MOTION_DURA_FRAMES = int((CLIP_FPS_FOR_RTC+1)/2)
UI_REFRESH_DURA_FRAMES = ONE_MINUTE_FRAMES

PREVIEW_W_SIZE  = 640
#PREVIEW_H_SIZE  = 360

HALF_MB_VALUE = 500*1024
ONE_MB_VALUE  = 1*1024*1024

MIN_VIDEO_FILE_SIZE = HALF_MB_VALUE


#FILEIN_ROOTPATH = r'c:\temp\in'
#FILEOUT_ROOTPATH = r'c:\temp\out'

FILEIN_ROOTPATH  = r'z:\calebroom'
FILEOUT_ROOTPATH = r'z:\calebroomcheck'

FILE_DAMAGED_VIDEO = 'damagedVideo.csv'
FILE_NO_MOTION     = 'NoMotionList.csv'

SRC_FOLDER_START   = 20150608