CLIP_FPS_FOR_RTC    = 14.635
ONE_MINUTE_FRAMES   = int(CLIP_FPS_FOR_RTC*60+1)

NOISE_WINDOW_SEC  = 10
NOISE_WINDOW_FRAME  = int(CLIP_FPS_FOR_RTC*NOISE_WINDOW_SEC)

MIN_MOTION_DURA_FRAMES = int((CLIP_FPS_FOR_RTC+1)/2)
UI_REFRESH_DURA_FRAMES = ONE_MINUTE_FRAMES

PREVIEW_W_SIZE  = 640
#PREVIEW_H_SIZE  = 360


FILEIN_ROOTPATH = r'c:\temp\in'
FILEOUT_ROOTPATH = r'c:\temp\out'

FILE_DAMAGED_VIDEO = 'damagedVideo.csv'
FILE_NO_MOTION     = 'NoMotionList.csv'

SRC_FOLDER_START   = 20161030